import { Activity, ArrowLeft, CheckCircle2, FileDown, MessageCircle, RotateCcw, ShieldAlert, Target, TrendingUp } from 'lucide-react';
import { points, severityLabels } from '../data/errors';
import { getResult, shareSummary, statusLabels, type ReportForm } from '../data/report';

type Props = {
  form: ReportForm;
  counts: Record<string, number>;
  notes: string;
  onResume: () => void;
  onReset: () => void;
};

export default function Report({ form, counts, notes, onResume, onReset }: Props) {
  const result = getResult(form, counts);
  const whatsapp = `https://wa.me/?text=${encodeURIComponent(shareSummary(form, result, notes))}`;
  return <>
    <header className="no-print border-b border-line bg-[#0d1627]"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-5 py-5 sm:px-8"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-500 text-white"><Activity size={22} strokeWidth={2.5} /></span><span className="text-lg font-black text-white">SHINPAN<span className="text-indigo-400">.</span></span></div><span className="rounded-full border border-indigo-400/30 bg-indigo-500/10 px-3 py-2 text-xs font-semibold text-indigo-200">Avaliação encerrada</span></div></header>
    <main className="report-print mx-auto max-w-5xl px-5 pb-20 pt-10 sm:px-8 sm:pt-14">
      <div className="mb-8 flex flex-wrap items-start justify-between gap-4"><div><span className="eyebrow">DEVOLUTIVA DE ARBITRAGEM</span><h1 className="mt-3 text-3xl font-extrabold tracking-tight text-white sm:text-4xl">Relatório de avaliação</h1><p className="mt-2 text-sm text-slate-400">Resultado calculado a partir das ocorrências registradas no tatame.</p></div><span className="rounded-lg border border-line bg-panel px-4 py-2 text-xs font-bold text-slate-300">TATAME {form.tatami}</span></div>
      <section className={`report-outcome report-outcome-${result.status}`} aria-label="Resultado da avaliação"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Resultado final</p><p className={`report-status report-status-${result.status} mt-3`}>{statusLabels[result.status]}</p><p className="mt-3 max-w-xl text-sm leading-relaxed text-slate-300">{result.reasons.join(' ')}</p></div><div className="report-score min-w-[140px] rounded-xl border border-line bg-[#0b1424] p-4 text-center"><p className="text-xs font-semibold uppercase tracking-widest text-slate-400">Pontuação</p><p className="mt-1 text-5xl font-black tabular-nums text-white">{result.score}<span className="text-base font-semibold text-slate-500">/100</span></p></div></div>{result.veto && <p className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-rose-300"><ShieldAlert size={18} />Critério de Veto Atingido</p>}</section>
      <section className="mt-6 grid gap-3 sm:grid-cols-2" aria-label="Identificação"><div className="summary-tile"><p className="report-label">Candidato</p><p className="mt-2 text-xl font-bold text-white">{form.candidate}</p><p className="mt-1 text-sm text-slate-400">{form.federation || 'Federação não informada'}</p></div><div className="summary-tile"><p className="report-label">Categorias</p><p className="mt-2 text-sm text-white">Atual: <strong>{form.current}</strong></p><p className="mt-1 text-sm text-white">Pleiteada: <strong>{form.target}</strong></p></div><div className="summary-tile"><p className="report-label">Avaliador</p><p className="mt-2 text-sm font-semibold text-white">{form.evaluator || 'Não informado'}</p></div><div className="summary-tile"><p className="report-label">Evento / Área</p><p className="mt-2 text-sm font-semibold text-white">{form.event || 'Evento não informado'} · Tatame {form.tatami}</p></div></section>
      <section className="mt-6 rounded-2xl border border-line bg-panel p-5 sm:p-7"><h2 className="flex items-center gap-2 text-lg font-bold text-white"><Target size={19} className="text-indigo-400" />Régua de avaliação</h2><div className="mt-5 grid gap-3 text-sm sm:grid-cols-3"><div className="report-metric"><span>Pontuação mínima</span><strong>{result.minimum} pts</strong></div><div className="report-metric"><span>Máximo de médios</span><strong>{result.medium} / {result.maxMedium}</strong></div><div className="report-metric"><span>Erros graves</span><strong>{result.grave} {result.noGrave ? '(limite 0)' : '(segurança: 0)'}</strong></div></div><p className="mt-4 text-xs leading-relaxed text-slate-400">Veto automático: qualquer erro grave de segurança ou 2 ocorrências graves de regra. Nas categorias Nacional e FIJ, nenhum erro grave é permitido.</p></section>
      <div className="mt-6 grid items-start gap-4 md:grid-cols-2"><section className="rounded-2xl border border-emerald-500/20 bg-panel p-5 sm:p-7"><h2 className="flex items-center gap-2 text-lg font-bold text-white"><CheckCircle2 size={19} className="text-emerald-400" />Pontos fortes</h2><p className="mt-2 text-sm text-slate-400">Áreas sem ocorrências registradas.</p>{result.strongGroups.length ? <ul className="mt-5 space-y-2">{result.strongGroups.map(group => <li key={group.id} className="flex items-center gap-2 text-sm font-medium text-emerald-300"><CheckCircle2 size={16} className="shrink-0" />{group.label}</li>)}</ul> : <p className="mt-5 text-sm text-slate-400">Todas as áreas tiveram ocorrências registradas.</p>}</section><section className="rounded-2xl border border-line bg-panel p-5 sm:p-7"><h2 className="flex items-center gap-2 text-lg font-bold text-white"><TrendingUp size={19} className="text-amber-400" />Resumo de ocorrências</h2><p className="mt-2 text-sm text-slate-400">Descontos aplicados à nota inicial de 100.</p><div className="mt-5 grid grid-cols-3 gap-2 text-center"><div className="report-metric"><strong>{result.total}</strong><span>Total</span></div><div className="report-metric"><strong>{result.medium}</strong><span>Médias</span></div><div className="report-metric"><strong>{result.grave}</strong><span>Graves</span></div></div></section></div>
      <section className="mt-6 rounded-2xl border border-line bg-panel p-5 sm:p-7"><h2 className="text-lg font-bold text-white">Oportunidades de melhoria</h2><p className="mt-2 text-sm text-slate-400">Detalhamento das ocorrências registradas.</p>{result.recorded.length ? <ul className="mt-5 divide-y divide-line">{result.recorded.map(({ item, quantity }) => <li key={item.id} className="flex flex-wrap items-start justify-between gap-x-4 gap-y-2 py-4 first:pt-0 last:pb-0"><div className="min-w-0 flex-1"><span className={`severity-tag severity-tag-${item.severity}`}>{severityLabels[item.severity]}{item.safety ? ' · Segurança' : ''}</span><p className="mt-2 text-sm leading-relaxed text-slate-200">{item.label}</p></div><div className="shrink-0 text-right text-sm"><strong className="text-white">×{quantity}</strong><p className="text-slate-400">−{quantity * points[item.severity]} pts</p></div></li>)}</ul> : <p className="mt-5 text-sm text-slate-400">Nenhuma ocorrência registrada.</p>}</section>
      {notes.trim() && <section className="mt-6 rounded-2xl border border-line bg-panel p-5 sm:p-7"><h2 className="text-lg font-bold text-white">Observações</h2><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-relaxed text-slate-300">{notes}</p></section>}
      <div className="no-print mt-8 grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => window.print()} className="primary-button"><FileDown size={18} />Exportar relatório / Imprimir (PDF)</button><a href={whatsapp} target="_blank" rel="noopener noreferrer" className="secondary-button text-center"><MessageCircle size={18} />Compartilhar resumo via WhatsApp</a><button type="button" onClick={onResume} className="secondary-button"><ArrowLeft size={18} />Retomar avaliação</button><button type="button" onClick={onReset} className="secondary-button"><RotateCcw size={18} />Nova avaliação</button></div><p className="no-print mt-4 text-center text-xs text-slate-500">Para salvar em PDF, escolha “Salvar como PDF” na janela de impressão. O WhatsApp requer conexão à internet.</p>
    </main>
  </>;
}
