import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import * as Tabs from '@radix-ui/react-tabs';
import { Activity, ArrowLeft, ArrowRight, ChevronRight, ClipboardCheck, Flag, Info, MapPin, Minus, Plus, RotateCcw, ShieldAlert, ShieldCheck } from 'lucide-react';
import { categories, errors, groups, points, severityLabels, type Category, type ErrorItem, type GroupId } from './data/errors';

const storageKey = 'shinpan-avaliacao-v1';
type Form = { candidate: string; federation: string; current: Category; target: Category; evaluator: string; event: string; tatami: string };
type Session = { screen: 'setup' | 'live' | 'finished'; form: Form; counts: Record<string, number>; notes: string; activeTab: GroupId };
const initial: Session = {
  screen: 'setup',
  form: { candidate: '', federation: '', current: 'Regional', target: 'Estadual', evaluator: '', event: '', tatami: '1' },
  counts: {}, notes: '', activeTab: 'regras',
};
function restore(): Session {
  try {
    const raw = localStorage.getItem(storageKey);
    if (!raw) return initial;
    const saved = JSON.parse(raw) as Partial<Session>;
    if (!saved.form || !saved.counts || !['setup', 'live', 'finished'].includes(saved.screen ?? '')) return initial;
    const validIds = new Set(errors.map(item => item.id));
    const counts = Object.fromEntries(Object.entries(saved.counts).filter(([key, value]) => validIds.has(key) && Number.isSafeInteger(value) && value >= 0));
    return { screen: saved.screen!, form: { ...initial.form, ...saved.form }, counts, notes: typeof saved.notes === 'string' ? saved.notes : '', activeTab: groups.some(group => group.id === saved.activeTab) ? saved.activeTab! : 'regras' };
  } catch { return initial; }
}
function Brand() {
  return <div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-500 text-white shadow-glow"><Activity size={22} strokeWidth={2.5} /></span><span className="text-lg font-black tracking-tight text-white">SHINPAN<span className="text-indigo-400">.</span></span></div>;
}
function Field({ label, children, optional = false }: { label: string; children: ReactNode; optional?: boolean }) {
  return <label className="block space-y-2"><span className="block text-sm font-semibold text-slate-200">{label}{optional && <span className="ml-2 text-xs font-normal text-slate-500">Opcional</span>}</span>{children}</label>;
}
function ErrorCard({ item, count, onChange }: { item: ErrorItem; count: number; onChange: (delta: number) => void }) {
  return <article className={`error-card severity-${item.severity} ${count > 0 ? 'is-active' : ''}`}>
    <div className="flex flex-1 flex-col justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><span className={`severity-tag severity-tag-${item.severity}`}>{severityLabels[item.severity]}</span><span className="text-xs font-semibold text-slate-400">−{points[item.severity]} pts</span>{item.safety && <span className="text-[11px] font-semibold text-rose-400">SEGURANÇA</span>}</div><h3 className="mt-3 text-sm font-semibold leading-relaxed text-slate-100 sm:text-[15px]">{item.label}</h3></div>
      <div className="flex items-center justify-between gap-3"><span className="text-xs text-slate-500">{count ? `${count} ocorrência${count > 1 ? 's' : ''}` : 'Nenhuma ocorrência'}</span><div className="flex items-center gap-2"><button type="button" onClick={() => onChange(-1)} disabled={!count} aria-label={`Remover ocorrência: ${item.label}`} className="counter-button counter-minus"><Minus size={18} /></button><span aria-live="polite" className="min-w-6 text-center text-lg font-bold tabular-nums text-white">{count}</span><button type="button" onClick={() => onChange(1)} aria-label={`Registrar ocorrência: ${item.label}`} className="counter-button counter-plus"><Plus size={19} /></button></div></div>
    </div>
  </article>;
}
export default function App() {
  const [session, setSession] = useState<Session>(restore);
  const { screen, form, counts, notes, activeTab } = session;
  useEffect(() => { try { localStorage.setItem(storageKey, JSON.stringify(session)); } catch { /* armazenamento indisponível */ } }, [session]);
  const count = (item: ErrorItem) => counts[item.id] ?? 0;
  const score = Math.max(0, 100 - errors.reduce((sum, item) => sum + count(item) * points[item.severity], 0));
  const totalErrors = errors.reduce((sum, item) => sum + count(item), 0);
  const veto = errors.some(item => item.safety && count(item) > 0) || errors.filter(item => item.group === 'regras' && item.severity === 'grave').reduce((sum, item) => sum + count(item), 0) >= 2;
  const updateForm = (key: keyof Form, value: string) => setSession(prev => ({ ...prev, form: { ...prev.form, [key]: value } }));
  const updateCount = (id: string, delta: number) => setSession(prev => ({ ...prev, counts: { ...prev.counts, [id]: Math.max(0, (prev.counts[id] ?? 0) + delta) } }));
  const start = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (form.candidate.trim()) setSession(prev => ({ ...prev, form: { ...prev.form, candidate: prev.form.candidate.trim() }, screen: 'live' })); };
  const finish = () => setSession(prev => ({ ...prev, screen: 'finished' }));
  const reset = () => { if (window.confirm('Iniciar uma nova avaliação? O registro atual será apagado deste dispositivo.')) setSession(initial); };
  return <div className="min-h-screen bg-ink text-slate-100">
    {screen === 'setup' && <>
      <header className="border-b border-line bg-[#0d1627]"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5 sm:px-8"><Brand /><span className="hidden text-xs font-semibold tracking-widest text-slate-500 sm:inline">SISTEMA DE AVALIAÇÃO DE ARBITRAGEM</span></div></header>
      <main className="mx-auto max-w-6xl px-5 pb-20 pt-10 sm:px-8 sm:pt-16"><div className="grid items-start gap-10 lg:grid-cols-[.85fr_1.15fr] lg:gap-16"><div className="lg:sticky lg:top-16"><span className="eyebrow">AVALIAÇÃO NO TATAME</span><h1 className="mt-5 text-4xl font-extrabold leading-tight tracking-tight text-white sm:text-5xl">Decisões precisas.<br /><span className="text-indigo-400">Avaliações justas.</span></h1><p className="mt-5 max-w-md leading-relaxed text-slate-400">Uma ferramenta para avaliar a arbitragem de judô em tempo real, com registro rápido e pontuação automática.</p><div className="mt-10 grid max-w-md gap-3"><div className="feature"><span className="feature-icon"><Plus size={19} /></span><div><p className="font-semibold text-white">Registro em um toque</p><p className="text-sm text-slate-400">Checklist preparado para a beira do tatame.</p></div></div><div className="feature"><span className="feature-icon"><Activity size={19} /></span><div><p className="font-semibold text-white">Pontuação em tempo real</p><p className="text-sm text-slate-400">Acompanhe cada ocorrência instantaneamente.</p></div></div><div className="feature"><span className="feature-icon"><ShieldCheck size={19} /></span><div><p className="font-semibold text-white">Dados no dispositivo</p><p className="text-sm text-slate-400">Continue sua avaliação mesmo sem internet.</p></div></div></div></div>
      <form onSubmit={start} className="rounded-2xl border border-line bg-panel p-5 shadow-2xl shadow-black/20 sm:p-8"><div className="flex items-start gap-3 border-b border-line pb-6"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-indigo-500/15 text-indigo-400"><ClipboardCheck size={22} /></span><div><h2 className="text-xl font-bold text-white">Nova avaliação</h2><p className="mt-1 text-sm text-slate-400">Preencha os dados para começar.</p></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Nome do candidato"><input className="field" autoComplete="name" required maxLength={120} placeholder="Nome completo do candidato" value={form.candidate} onChange={e => updateForm('candidate', e.target.value)} /></Field></div><Field label="Federação / Associação" optional><input className="field" maxLength={120} placeholder="Ex.: Federação Estadual" value={form.federation} onChange={e => updateForm('federation', e.target.value)} /></Field><Field label="Nome do avaliador" optional><input className="field" maxLength={120} placeholder="Nome do avaliador" value={form.evaluator} onChange={e => updateForm('evaluator', e.target.value)} /></Field><Field label="Categoria atual"><select className="field" value={form.current} onChange={e => updateForm('current', e.target.value)}>{categories.slice(0, 5).map(c => <option key={c}>{c}</option>)}</select></Field><Field label="Categoria pleiteada"><select className="field" value={form.target} onChange={e => updateForm('target', e.target.value)}>{categories.map(c => <option key={c}>{c}</option>)}</select></Field><Field label="Evento / Campeonato" optional><input className="field" maxLength={120} placeholder="Ex.: Campeonato Estadual" value={form.event} onChange={e => updateForm('event', e.target.value)} /></Field><Field label="Tatame / Área"><select className="field" value={form.tatami} onChange={e => updateForm('tatami', e.target.value)}>{Array.from({ length: 12 }, (_, i) => <option key={i + 1} value={i + 1}>Tatame {i + 1}</option>)}</select></Field></div><div className="mt-7 rounded-xl border border-indigo-400/20 bg-indigo-500/5 p-4 text-sm text-slate-400"><Info size={17} className="mr-2 inline-block align-text-bottom text-indigo-400" />O progresso é salvo automaticamente neste dispositivo.</div><button type="submit" className="primary-button mt-6 w-full">Iniciar Avaliação no Tatame <ArrowRight size={19} /></button></form></div></main>
    </>}
    {screen === 'live' && <>
      <header className="sticky top-0 z-30 border-b border-line bg-[#0d1627]/95 shadow-xl shadow-black/10 backdrop-blur-lg"><div className="mx-auto max-w-6xl px-4 py-3 sm:px-8"><div className="flex flex-wrap items-center justify-between gap-3"><Brand /><div className="flex items-center gap-4"><div className="hidden text-right sm:block"><p className="text-[11px] font-semibold uppercase tracking-widest text-slate-500">Pontuação atual</p><p aria-live="polite" className={`text-3xl font-black leading-none tabular-nums ${score < 70 ? 'text-rose-400' : 'text-white'}`}>{score}<span className="ml-1 text-sm font-medium text-slate-500">/ 100</span></p></div><button type="button" onClick={finish} className="flex min-h-12 items-center gap-2 rounded-xl border border-indigo-400/40 bg-indigo-500/10 px-3 text-xs font-bold text-indigo-200 transition hover:bg-indigo-500/20 sm:px-5 sm:text-sm">Encerrar luta <ChevronRight size={17} /></button></div></div><div className="mt-3 flex flex-wrap items-center justify-between gap-x-4 gap-y-2 border-t border-line/70 pt-3"><div className="flex min-w-0 items-center gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-indigo-500/15 text-xs font-bold text-indigo-300">{form.candidate.trim().slice(0, 2).toUpperCase()}</span><div className="min-w-0"><p className="truncate text-sm font-bold text-white">{form.candidate}</p><p className="text-xs text-slate-400">{form.target} · Tatame {form.tatami}</p></div></div><div className="flex items-center gap-2"><span className="text-xs font-semibold tabular-nums text-slate-400 sm:hidden">{score}/100 pts</span>{veto ? <span className="veto-badge"><ShieldAlert size={15} />Critério de Veto Atingido</span> : <span className="flex items-center gap-1.5 text-xs font-medium text-emerald-400"><ShieldCheck size={15} />Sem veto</span>}</div></div><div className="mt-3 h-1 overflow-hidden rounded-full bg-slate-700"><div className={`h-full rounded-full transition-all duration-300 ${score < 70 ? 'bg-rose-500' : score < 90 ? 'bg-amber-400' : 'bg-indigo-400'}`} style={{ width: `${score}%` }} /></div></div></header>
      <main className="mx-auto max-w-6xl px-4 pb-24 pt-7 sm:px-8 sm:pt-10"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><span className="eyebrow">AVALIAÇÃO EM ANDAMENTO</span><h1 className="mt-3 text-2xl font-extrabold tracking-tight text-white sm:text-3xl">Registro de ocorrências</h1><p className="mt-2 text-sm text-slate-400">Toque em + para registrar uma ocorrência. Use − para corrigir.</p></div><div className="rounded-xl border border-line bg-panel px-4 py-3 text-center"><p className="text-2xl font-black leading-none tabular-nums text-white">{totalErrors}</p><p className="mt-1 text-[10px] font-semibold uppercase tracking-wider text-slate-400">Ocorrências</p></div></div>
        <Tabs.Root value={activeTab} onValueChange={value => setSession(prev => ({ ...prev, activeTab: value as GroupId }))}><Tabs.List aria-label="Categorias de erros" className="mb-7 flex gap-2 overflow-x-auto border-b border-line pb-3">{groups.map(group => { const quantity = errors.filter(item => item.group === group.id).reduce((sum, item) => sum + count(item), 0); return <Tabs.Trigger key={group.id} value={group.id} className="tab-button"><span className="hidden sm:inline">{group.label}</span><span className="sm:hidden">{group.short}</span>{quantity > 0 && <span className="flex h-5 min-w-5 items-center justify-center rounded-full bg-indigo-400/20 px-1 text-[11px] text-indigo-200">{quantity}</span>}</Tabs.Trigger>; })}</Tabs.List>{groups.map(group => <Tabs.Content key={group.id} value={group.id} className="outline-none"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold text-white">{group.label}</h2><p className="mt-1 text-sm text-slate-400">{group.description}</p></div><span className="text-xs text-slate-500">{errors.filter(item => item.group === group.id).length} critérios</span></div><div className="grid gap-3 lg:grid-cols-2">{errors.filter(item => item.group === group.id).map(item => <ErrorCard key={item.id} item={item} count={count(item)} onChange={delta => updateCount(item.id, delta)} />)}</div></Tabs.Content>)}</Tabs.Root>
        <section className="mt-9 rounded-2xl border border-line bg-panel p-5 sm:p-7"><div className="mb-3 flex items-center gap-2"><ClipboardCheck size={18} className="text-indigo-400" /><label htmlFor="notes" className="text-sm font-bold text-white">Observações rápidas</label></div><textarea id="notes" rows={3} value={notes} onChange={event => setSession(prev => ({ ...prev, notes: event.target.value }))} placeholder="Ex.: Revisão de Care System no minuto 02:40..." className="field min-h-[100px] resize-y" /><p className="mt-2 text-xs text-slate-500">As anotações são salvas automaticamente neste dispositivo.</p></section><div className="mt-7 flex flex-wrap items-center justify-between gap-4"><span className="flex items-center gap-2 text-xs text-slate-500"><MapPin size={15} /> Tatame {form.tatami} {form.event && `· ${form.event}`}</span><button type="button" onClick={finish} className="primary-button w-full sm:w-auto">Encerrar luta / Finalizar avaliação <Flag size={18} /></button></div>
      </main>
    </>}
    {screen === 'finished' && <>
      <header className="border-b border-line bg-[#0d1627]"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-5 py-5 sm:px-8"><Brand /><span className="rounded-full border border-indigo-400/30 bg-indigo-500/10 px-3 py-2 text-xs font-semibold text-indigo-200">Avaliação encerrada</span></div></header>
      <main className="mx-auto max-w-3xl px-5 py-12 sm:px-8 sm:py-20"><span className="eyebrow">REGISTRO SALVO NESTE DISPOSITIVO</span><h1 className="mt-4 text-3xl font-extrabold text-white sm:text-4xl">Avaliação encerrada</h1><p className="mt-3 text-slate-400">Confira o registro antes de iniciar uma nova avaliação. A devolutiva completa estará disponível na próxima etapa.</p>
        <div className="mt-9 grid gap-3 sm:grid-cols-3"><div className="summary-tile sm:col-span-2"><p className="text-xs uppercase tracking-widest text-slate-400">Candidato</p><p className="mt-2 text-xl font-bold text-white">{form.candidate}</p><p className="mt-1 text-sm text-slate-400">{form.target} · Tatame {form.tatami}</p></div><div className="summary-tile"><p className="text-xs uppercase tracking-widest text-slate-400">Pontuação</p><p className="mt-2 text-4xl font-black tabular-nums text-white">{score}<span className="text-base text-slate-500"> / 100</span></p></div></div>
        {veto && <p className="veto-badge mt-5"><ShieldAlert size={16} />Critério de Veto Atingido</p>}
        <div className="mt-6 rounded-2xl border border-line bg-panel p-5 sm:p-7"><h2 className="text-lg font-bold text-white">Ocorrências registradas <span className="ml-1 text-indigo-400">({totalErrors})</span></h2>{totalErrors ? <ul className="mt-4 divide-y divide-line">{errors.filter(item => count(item) > 0).map(item => <li key={item.id} className="flex items-start justify-between gap-4 py-3 text-sm text-slate-300"><span>{item.label}</span><span className="shrink-0 font-bold text-white">×{count(item)}</span></li>)}</ul> : <p className="mt-4 text-sm text-slate-400">Nenhuma ocorrência registrada.</p>}{notes && <div className="mt-5 border-t border-line pt-5"><p className="mb-2 text-xs font-bold uppercase tracking-widest text-slate-400">Observações</p><p className="whitespace-pre-wrap text-sm text-slate-300">{notes}</p></div>}</div>
        <div className="mt-7 flex flex-wrap gap-3"><button type="button" onClick={() => setSession(prev => ({ ...prev, screen: 'live' }))} className="secondary-button"><ArrowLeft size={18} /> Retomar avaliação</button><button type="button" onClick={reset} className="primary-button"><RotateCcw size={18} /> Nova avaliação</button></div>
      </main>
    </>}
  </div>;
}
